module com.mycompany.restaurant {

    requires transitive javafx.controls;
    requires transitive javafx.graphics;
    requires javafx.fxml;
    requires transitive java.sql;
    requires java.base;

    opens restaurant to javafx.fxml;
    opens Login to javafx.fxml;
    opens dashboard to javafx.fxml;
    opens bill to javafx.fxml;
    opens booking to javafx.fxml;
    opens category to javafx.fxml;
    opens customer to javafx.fxml;
    opens customer.controller.customerhome to javafx.fxml;
    opens customer.controller.menu to javafx.fxml;
    opens customer.controller.fooddetail to javafx.fxml;
    opens customer.controller.cart to javafx.fxml;
    opens customer.controller.checkout to javafx.fxml;
    opens customer.controller.payment to javafx.fxml;
    opens customer.controller.booking to javafx.fxml;
    opens customer.controller.bookingdetail to javafx.fxml;
    opens customer.controller.order to javafx.fxml;
    opens customer.controller.orderdetail to javafx.fxml;
    opens customer.controller.history to javafx.fxml;
    opens customer.controller.historydetail to javafx.fxml;
    opens customer.controller.notification to javafx.fxml;
    opens customer.controller.profile to javafx.fxml;
    opens customer.controller.favorite to javafx.fxml;
    opens customer.controller.component to javafx.fxml;
    opens customer.controller.common to javafx.fxml;
    opens customer.controller.util to javafx.fxml;
    opens employee to javafx.fxml;
    opens food to javafx.fxml;
    opens importreceipt to javafx.fxml;
    opens shift to javafx.fxml;
    opens supplier to javafx.fxml;
    opens table to javafx.fxml;
    opens warehouse to javafx.fxml;
    opens account to javafx.fxml;
    opens recipe to javafx.fxml;
    opens model to javafx.fxml;
    opens order to javafx.fxml;

    exports restaurant;
    exports Login;
    exports dashboard;
    exports bill;
    exports booking;
    exports category;
    exports customer;
    exports customer.controller.customerhome;
    exports customer.controller.menu;
    exports customer.controller.fooddetail;
    exports customer.controller.cart;
    exports customer.controller.checkout;
    exports customer.controller.payment;
    exports customer.controller.booking;
    exports customer.controller.bookingdetail;
    exports customer.controller.order;
    exports customer.controller.orderdetail;
    exports customer.controller.history;
    exports customer.controller.historydetail;
    exports customer.controller.notification;
    exports customer.controller.profile;
    exports customer.controller.favorite;
    exports customer.controller.component;
    exports customer.controller.common;
    exports customer.controller.util;
    exports employee;
    exports food;
    exports importreceipt;
    exports shift;
    exports supplier;
    exports table;
    exports warehouse;
    exports account;
    exports recipe;
    exports model;
    exports order;
}